apiVersion: v1 
kind: ConfigMap 
metadata:
  namespace: hfbn
  name: ca-config
data:
  FABRIC_ORGS: org0 org1
  FABRIC_CA_SERVER_DEBUG: "true"
  FABRIC_CA_SERVER_HOME: /etc/hyperledger/fabric-ca
  FABRIC_CA_SERVER_TLS_ENABLED: "true"

---

apiVersion: v1 
kind: ConfigMap 
metadata:
  namespace: hfbn
  name: ica-config
data:
  FABRIC_CA_SERVER_CSR_HOSTS: ica-0.ica-svc.hfbn.svc.cluster.local
  FABRIC_CA_SERVER_CA_NAME: ica-0.ica-svc.hfbn.svc.cluster.local
  FABRIC_CA_SERVER_INTERMEDIATE_TLS_CERTFILES: /data/ca-cert.pem
  PARENT_URL: https://rca.hf.m.io-admin:adminpw@rca-0.rca-svc.hfbn.svc.cluster.local:7054
  FABRIC_CA_CLIENT_TLS_CERTFILES: /etc/hyperledger/fabric-ca/ca-chain.pem

---

apiVersion: v1 
kind: ConfigMap 
metadata:
  namespace: hfbn
  name: orderer-config
data:
  GODEBUG: "netdns=go"
  ORDERER_GENERAL_LOGLEVEL: debug
  ORDERER_GENERAL_GENESISPROFILE: OrdererMyCreditChain
  ORDERER_GENERAL_GENESISMETHOD: file
  ORDERER_GENERAL_GENESISFILE: /data/orderer.genesis.block
  ORDERER_GENERAL_LOCALMSPID: hf.m.io
  ORDERER_GENERAL_TLS_ENABLED: "true"
  ORDERER_GENERAL_TLS_ROOTCAS: "[/data/org0-ca-chain.pem]"
  ORDERER_GENERAL_CLUSTER_ROOTCAS: "[/data/org0-ca-chain.pem]"
  CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE: bridge
  ORDERER_GENERAL_LISTENPORT: "7050"

---

apiVersion: v1 
kind: ConfigMap 
metadata:
  namespace: hfbn
  name: peer-config
data:
  GODEBUG: "netdns=go"
  CORE_VM_ENDPOINT: "unix:///host/var/run/docker.sock"
  CORE_VM_DOCKER_ATTACHSTDOUT: "true"
  FABRIC_LOGGING_SPEC: DEBUG
  CORE_METRICS_PROVIDER: prometheus
  CORE_PEER_TLS_ENABLED: "true"
  CORE_PEER_TLS_ROOTCERT_FILE: /data/org1-ca-chain.pem
  CORE_PEER_ADDRESSAUTODETECT: "true"
  CORE_PEER_GOSSIP_USELEADERELECTION: "true"
  CORE_PEER_LOCALMSPID: org1.hf.m.io
  CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE: bridge
  CORE_PEER_MSPCONFIGPATH: /data/peerOrganizations/org1.hf.m.io/users/admin/msp/


