apiVersion: v1
kind: Service
metadata:
  namespace: hfbn
  name: peer0-svc
spec:
  type: ClusterIP
  selector:
    hfbn: peer0
  ports:
  - name: peer0-1
    port: 7051
    targetPort: 7051
  - name: peer0-2
    port: 7053
    targetPort: 7053
  - name: peer0-3
    port: 9443
    targetPort: 9443

---

apiVersion: v1
kind: Service
metadata:
  namespace: hfbn
  name: peer1-svc
spec:
  type: ClusterIP
  selector:
    hfbn: peer1
  ports:
  - name: peer1-1
    port: 7051
    targetPort: 7051
  - name: peer1-2
    port: 7053
    targetPort: 7053
  - name: peer1-3
    port: 9443
    targetPort: 9443

---

apiVersion: v1
kind: Service
metadata:
  namespace: hfbn
  name: peer2-svc
spec:
  type: ClusterIP
  selector:
    hfbn: peer2
  ports:
  - name: peer2-1
    port: 7051
    targetPort: 7051
  - name: peer2-2
    port: 7053
    targetPort: 7053
  - name: peer2-3
    port: 9443
    targetPort: 9443

